name: Release to Heroku

on:
  push:
    branches:
      - development
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          SLACK_BOT_TOKEN: ${{ secrets.DEV_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.DEV_SIGNING_SECRET }}
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "hh-slack-bot"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
