on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    
  test:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          SLACK_BOT_TOKEN: ${{ secrets.DEV_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.DEV_SIGNING_SECRET }}