on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
      - development
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Checkstyle lint check
        run: mvn checkstyle:check
        
  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Test with coverage
        run: mvn --batch-mode --update-snapshots verify -P coverage
        env:
          SLACK_BOT_TOKEN: ${{ secrets.DEV_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.DEV_SIGNING_SECRET }}

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60